#!/usr/bin/env node
/**
 * Generate the static stylesheet for a prefix.
 *
 *   node scripts/build-css.mjs                      # css/signals.css, prefix "sig"
 *   node scripts/build-css.mjs --prefix app         # --app-* names
 *   node scripts/build-css.mjs --prefix "" --out public/signals.css
 *   node scripts/build-css.mjs --raw                # include raw scroll px values
 *
 * Also writes the CSS functions (--{prefix}-progress() etc.) next to it, or to --utils-out.
 * Only properties whose names are known ahead of time are emitted; the rest
 * (key codes, gamepad buttons, input names) are registered by the runtime.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { parseArgs } from "node:util";
import {
  cycle, date, framed, gamepad, input, keyboard, pointer, random, scroll, viewport,
} from "../src/sources/index.mjs";
import { functionsCss, sourcesCss } from "../src/css.mjs";

const { values } = parseArgs({
  options: {
    prefix: { type: "string", default: "sig" },
    out: { type: "string", default: "css/signals.css" },
    "utils-out": { type: "string", default: "css/utils.css" },
    raw: { type: "boolean", default: false },
  },
});

if (values.prefix !== "" && !/^[A-Za-z_][A-Za-z0-9_-]*$/.test(values.prefix)) {
  console.error(`Invalid prefix ${JSON.stringify(values.prefix)}.`);
  process.exit(1);
}

const header = `/* Generated by scripts/build-css.mjs -- prefix: ${JSON.stringify(values.prefix)}. Do not edit. */\n\n`;
const css =
  header +
  sourcesCss(values.prefix, [
    pointer(),
    scroll({ raw: values.raw }),
    viewport(),
    keyboard(),
    date(),
    date({ utc: true }),
    framed(),
    random(),
    // Mostly runtime-named (pad buttons, input and cycle names); only the
    // pad `connected` flags are known ahead of time.
    gamepad(),
    input(),
    cycle(),
  ]);

for (const [file, text] of [
  [values.out, css],
  [values["utils-out"], header + functionsCss(values.prefix)],
]) {
  const path = resolve(file);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, text);
  console.log(`wrote ${file}`);
}
